apiVersion: v1
kind: ConfigMap
metadata:
  name: student-config
  namespace: student-management
data:
  DB_HOST: "mysql" # Replace with actual AWS EC2 IP or hostname
  DB_PORT: "3306"
  DB_NAME: "studentdb"
  SPRING_PROFILES_ACTIVE: "prod"
