apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-pvc
  namespace: student-management
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
